-- Inserir dados na tabela LEILAO
INSERT INTO LEILAO (DESCRICAO, VALOR_MINIMO, STATUS) VALUES ('Estatua Torre', 250, 0);
INSERT INTO LEILAO (DESCRICAO, VALOR_MINIMO, STATUS) VALUES ('Jogo Americano', 350, 0);
INSERT INTO LEILAO (DESCRICAO, VALOR_MINIMO, STATUS) VALUES ('Monalisa', 2500000000, 0);

-- Inserir dados na tabela USUARIO
INSERT INTO USUARIO (EMAIL, NOME, SENHA) VALUES ('usuario1@example.com', 'Usuário 1', 'senha123');
INSERT INTO USUARIO (EMAIL, NOME, SENHA) VALUES ('usuario2@example.com', 'Usuário 2', 'senha456');

-- Inserir dados na tabela CONCORRENTE
INSERT INTO CONCORRENTE (CPF, NOME) VALUES ('12345678901', 'Concorrente 1');
INSERT INTO CONCORRENTE (CPF, NOME) VALUES ('98765432109', 'Concorrente 2');
